Month9/step1
IrinaVinit/Stellar-Burgers pull request #5
Opened 2023-03-08 08:03 UTC by IrinaVinit

Добрый день! Высылаю на ревью первую часть проекта.

2023-03-08 09:07 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 

Что понравилось:
- Роутинг настроен и работает правильно
- Реализован механизм обновления токена
- Данные с форм отправляютя по `onSubmit`

Однако есть пару моментов, которые необходимо поправить:
- Если открыть по прямой ссылке ингредиент, то его потом невозможно закрыть, ни нажатием на крестик ни на ESC.

https://user-images.githubusercontent.com/60173362/223661919-10af5c0f-2856-4798-a569-c5a2709483ac.mov

- Невозможно изменить пароль с помощью формы в личном кабинете.  Невозможно разблокировать инпут.

- Если в куках нет токена, то нет смысла и делать запрос на получение данных юзера.
- При нажатии "Зарегистрироваться" пользователь остается на том же роуте. Роут `register` не работает.
- Обновления протухшего токена не работает. При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя. 
![Снимок экрана 2023-03-08 в 12 07 08](https://user-images.githubusercontent.com/60173362/223670480-913a79bc-443e-48f3-b7ee-c9e7a03086f1.png)

**Можно лучше**
- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью  `return <Redirect to={location?.state?.from || '/'} />; `(эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Redirect`)

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-08 09:07 UTC, andryxxa93 commented on src/components/app-header/AppHeader.jsx
> +  const { userData } = useSelector((state) => state.user);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-08 09:07 UTC, andryxxa93 commented on src/components/app/App.jsx
> +        <Route path="/register" element={<ProtectedRouteElement element={<Register />}/>} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-08 09:07 UTC, andryxxa93 commented on src/components/ingredient/Ingredient.jsx
>  const Ingredient = ({ data, name, price, image, type }) => {
**Можно лучше**

используйте для компонентов обертку React.memo, которая позволяет сократить количество лишних рендеров и улучшить производительность

Например:

```
const SomeComponent = () => {
  return (
     ...........
  );
};

export default React.memo(SomeComponent);
```

https://ru.reactjs.org/docs/react-api.html#reactmemo
https://habr.com/ru/company/plarium/blog/442116/

2023-03-11 16:12 UTC, IrinaVinit commented on src/components/app-header/AppHeader.jsx
> +  const { userData } = useSelector((state) => state.user);
Спасибо, готово!

2023-03-11 16:12 UTC, IrinaVinit commented on src/components/app/App.jsx
> +        <Route path="/register" element={<ProtectedRouteElement element={<Register />}/>} />
Готово

2023-03-11 16:15 UTC, IrinaVinit commented on src/components/ingredient/Ingredient.jsx
>  const Ingredient = ({ data, name, price, image, type }) => {
Ух ты, не знала..

2023-03-12 05:51 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-14 23:39 UTC, merged