Month10/step
IrinaVinit/Stellar-Burgers pull request #7
Opened 2023-08-22 12:26 UTC by IrinaVinit

2023-08-22 13:05 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая типизация `redux`
- Созданы все необходимые утилитарные типы
- Не использовали `ts-ignore`

Необходимо исправить:
- В проекте присутствует `any` от которых можно избавиться
- Конкретизируйте тип возвращаемого значения в фукнциях `checkResponse ` и `fetchWithRefresh `

Более подробно описание проблемы смотрите комментарии в pull request.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-22 13:05 UTC, andryxxa93 commented on src/components/profile-form/ProfileForm.tsx
> +  // useEffect(() => {
**Можно улучшить**
Ненужный код лучше удалять

2023-08-22 13:05 UTC, andryxxa93 commented on src/components/utils/data.ts
> +export function checkResponse(res: Response) {
**Необходимо исправить**
- В текущем виде функция checkResponse не конкретизирует тип возвращаемого значения в теле ответа, поэтому все последующие функции связанные с ней работают с any, что не позволяет TypeScript отследить корректность вашего кода.

```js
const checkResponse = <T>(res: Response): Promise<T> => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

Аналогично этому следует скорректировать функцию `fetchWithRefresh`

2023-08-22 13:48 UTC, IrinaVinit commented on src/components/profile-form/ProfileForm.tsx
> +  // useEffect(() => {
Готово

2023-08-24 10:23 UTC, IrinaVinit commented on src/components/utils/data.ts
> +export function checkResponse(res: Response) {
Готово.

2023-08-24 16:52 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-25 13:53 UTC, merged